// english letter frequency
export default [
    { 'letter': 'a', 'value': 8.167 },
    { 'letter': 'b', 'value': 1.492 },
    { 'letter': 'c', 'value': 2.782 },
    { 'letter': 'd', 'value': 4.253 },
    { 'letter': 'e', 'value': 12.702 },
    { 'letter': 'f', 'value': 2.228 },
    { 'letter': 'g', 'value': 2.015 },
    { 'letter': 'h', 'value': 6.094 },
    { 'letter': 'i', 'value': 6.966 },
    { 'letter': 'j', 'value': 0.153 },
    { 'letter': 'k', 'value': 0.772 },
    { 'letter': 'l', 'value': 4.025 },
    { 'letter': 'm', 'value': 2.406 },
    { 'letter': 'n', 'value': 6.749 },
    { 'letter': 'o', 'value': 7.507 },
    { 'letter': 'p', 'value': 1.929 },
    { 'letter': 'q', 'value': 0.095 },
    { 'letter': 'r', 'value': 5.987 },
    { 'letter': 's', 'value': 6.327 },
    { 'letter': 't', 'value': 9.056 },
    { 'letter': 'u', 'value': 2.758 },
    { 'letter': 'v', 'value': 0.978 },
    { 'letter': 'w', 'value': 2.36 },
    { 'letter': 'x', 'value': 0.15 },
    { 'letter': 'y', 'value': 1.974 },
    { 'letter': 'z', 'value': 0.074 }
];